### ISSUE TITLE
traitlets did not install from the git clone

### ISSUE THREAD

**Issue by pradipta03** [DavidMachineLearning/jetson_configuration#1]
Device : Nano 4gb with Tplink wifi dongle
Since I was having issues with running the bash file so I tried to check with ethernet connection. I had the same result with as the wifi (I was assuming wifi was being disrupted so checked with an ethernet cable. ) . 

Later , I tried running your bash comment manually in the terminal one by one. 
Then I figured out that this is the line where I am having an error. >> echo $password | sudo -S python3 -m pip install git+https://github.com/ipython/traitlets@master

The error report is >> > WARNING: Discarding git+https://github.com/ipython/traitlets@master. Command err                                                                                                                                                          ored out with exit status 1: git checkout -q master Check the logs for full comm                                                                                                                                                             and output.
> ERROR: Command errored out with exit status 1: git checkout -q master Check the                                                                                                                                                              logs for full command output.

By the way what is the function of traitlets in the code?

**Comment by pradipta03** [comment]
I installed all the dependencies from the bash script manually. 

While doing so I figured out the main issue is in some occasion internet connection gets interrupted. That is where the problem starts. 

Since I did it manually copying all the lines one by one in the terminal I was able to track the interruption and redo it when needed. 
I had some error in the process while installing TF1 and TF2 . Some version issue. But I have the jupyterlab running with TF1,TF2 and pytorch. So lets see. 

Thank you for your work.

**Comment by pradipta03** [comment]
> Device : Nano 4gb with Tplink wifi dongle
> Since I was having issues with running the bash file so I tried to check with ethernet connection. I had the same result with as the wifi (I was assuming wifi was being disrupted so checked with an ethernet cable. ) .
> 
> Later , I tried running your bash comment manually in the terminal one by one.
> Then I figured out that this is the line where I am having an error. >> echo $password | sudo -S python3 -m pip install git+https://github.com/ipython/traitlets@master
> 
> The error report is >> > WARNING: Discarding git+https://github.com/ipython/traitlets@master. Command err ored out with exit status 1: git checkout -q master Check the logs for full comm and output.
> 
> > ERROR: Command errored out with exit status 1: git checkout -q master Check the                                                                                                                                                              logs for full command output.
> 
> By the way what is the function of traitlets in the code?

**Comment by DavidMachineLearning** [comment]
Great, thank you for letting me know.
